# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Blog Posts
    url: "#post"
    weight: 10
  - name: DFS
    url: "#dfs"
    weight: 20
  - name: Betting
    url: '#posts'
    weight: 30
  - name: Live Leaderboard
    url: '#about'
    weight: 40
  - name: Course Key Stats
    url: '#projects'
    weight: 50
  - name: Blog Posts  
    url: '#featured'
    weight: 60
